const INCREMENT = 'INCREMENT';

const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_FAIL = 'SIGNUP_FAIL';
const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
const SIGNIN_FAIL = 'SIGNIN_FAIL';

const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST';
const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
const GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL';

const GET_STATIC_DATA_SUCCESS = 'GET_STATIC_DATA_SUCCESS';
const GET_STATIC_DATA_FAIL = 'GET_STATIC_DATA_FAIL';

const UPDATE_LOCALIZAITON_LANGUAGE = 'UPDATE_LOCALIZAITON_LANGUAGE';
const UPDATE_LOCALIZAITON_TIMEZONE = 'UPDATE_LOCALIZAITON_TIMEZONE';
const UPDATE_LOCALIZAITON_CURRENCY = 'UPDATE_LOCALIZAITON_CURRENCY';

const UPDATE_USER_DATA_REQUEST = 'UPDATE_USER_DATA_REQUEST';
const UPDATE_USER_DATA_SUCCESS = 'UPDATE_USER_DATA_SUCCESS';
const UPDATE_USER_DATA_FAIL = 'UPDATE_USER_DATA_FAIL';


export {
  INCREMENT,
  SIGNUP_REQUEST,
  SIGNUP_SUCCESS,
  SIGNUP_FAIL,
  SIGNIN_REQUEST,
  SIGNIN_SUCCESS,
  SIGNIN_FAIL,
  GET_USER_DATA_REQUEST,
  GET_USER_DATA_SUCCESS,
  GET_USER_DATA_FAIL,
  GET_STATIC_DATA_SUCCESS,
  GET_STATIC_DATA_FAIL,
  UPDATE_LOCALIZAITON_LANGUAGE,
  UPDATE_LOCALIZAITON_TIMEZONE,
  UPDATE_LOCALIZAITON_CURRENCY,
  UPDATE_USER_DATA_REQUEST,
  UPDATE_USER_DATA_SUCCESS,
  UPDATE_USER_DATA_FAIL,
};
